development:
  adapter: postgresql
  encoding: unicode
  database: calendly_integration_development
  pool: 5
  username: postgres
  password:
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: calendly_integration_test
  pool: 5
  username: postgres
  password:
  timeout: 5000
